### PR TITLE
Created Home Landing Page [Needs to be filled with the content]

### LINKED ISSUE #29: Landing Screen
Design and create the landing page for the application

### PR DESCRIPTION
**Pull request by mohamedsgap**
Crated the page structure and boilerplate of the Home Landing #29, as we confirmed before we only just to update the page with our  unique content, adapt out color theme, replace the existing legacy images with our own!

--> NOW 
You need to fetch this [WIP] PR in you local machines, and start updating the content! 
@mwissem @AbdullahMuhammed5 @aashrafh

### CODE REVIEW

**Comment by mohamedsgap** [comment]
hey guys @aashrafh @AbdullahMuhammed5 @mwissem any updates regarding the content ??

**Review by ghost — DISMISSED** [review]

**Comment by ghost** [comment]
@mohamedsgap  You have conflicted files.

**Comment by mohamedsgap** [comment]
@mwissem @AbdullahMuhammed5 @aashrafh no worries about the conflict files and Codacy  just fetch this PR on your local machines and push back the updated contents!

**Comment by mohamedsgap** [comment]
@AbdullahMuhammed5  `Codacy` issues because of the way the code formatted, using single quote instead of double quote, I gonna fix this later today!

**Comment by AbdullahMuhammed5** [comment]
Acceptance qualifications are added to landing page.

Screenshot from 2020-09-29 09-43-41

**Pull request closed without merging**
