### PR TITLE
login page, added (type, error, helperText) to TextField

### PR DESCRIPTION
**Pull request by ghost**
BabeJo_login

### CODE REVIEW

**Review by aashrafh — DISMISSED** [review]

**Review by AbdullahMuhammed5 — DISMISSED** [review]

**Comment by AbdullahMuhammed5** [comment]
Great work @mwissem everything is great just unit test is needed.

**Review by mohamedsgap — DISMISSED** [review]
LGTM :+1:

**Comment by ghost** [comment]
I will add unittest plus `remember me` and `forget password`

**Comment by RanaEmad** [comment]
Please, resolve the conflicts @mwissem so that I could merge this PR.

**Review by mohamedsgap — APPROVED** [review]

**Review by AbdullahMuhammed5 — APPROVED** [review]

**Review by RanaEmad — APPROVED** [review]

**Pull request merged**
